create schema SAVER;


DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS AUTHORITY;
DROP TABLE IF EXISTS USER_AUTHORITY;

CREATE TABLE USER (
    ID int  PRIMARY KEY,
    USERNAME VARCHAR (255),
    PASSWORD VARCHAR (255),
    FIRSTNAME VARCHAR (255),
    LASTNAME VARCHAR (255),
    EMAIL VARCHAR (255),
    ENABLED NUMERIC (1)
);

CREATE TABLE AUTHORITY (
    ID int PRIMARY KEY,
    NAME VARCHAR (255)
);

CREATE TABLE USER_AUTHORITY (
    USER_ID VARCHAR (255),
    AUTHORITY_ID VARCHAR (255),
   CONSTRAINT FK_EMP_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER(ID),
   CONSTRAINT FK_EMP_AUTH_ID FOREIGN KEY(AUTHORITY_ID) REFERENCES AUTHORITY(ID)
);

